### ISSUE TITLE
How can this project be run?

### ISSUE THREAD

**Issue by jamesmcnamara** [scalagen/scalagen#3]
Hi! Thank you so much for forking this and trying to keep it up to date.

How would you go about actually running this fork in or on an existing maven project?

Thanks!

**Comment by nightscape** [comment]
Hi @jamesmcnamara, I just updated the README with what I would assume should give you a working command line app:
https://github.com/scalagen/scalagen/blob/master/README.md#development
Can't test it right now, but let me know if it works :wink:

**Comment by jamesmcnamara** [comment]
Thanks! I'll try it out :)

**Comment by jamesmcnamara** [comment]
Unfortunately it crashes with the following error:
```sh
[info] Loading project definition from /Users/my-user-name/projects/scalagen/project
java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1261)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1334)
	at sbt.IO$.pathSplit(IO.scala:797)
	at sbt.IO$.parseClasspath(IO.scala:912)
	at sbt.compiler.CompilerArguments.extClasspath(CompilerArguments.scala:66)
	at sbt.compiler.MixedAnalyzingCompiler$.withBootclasspath(MixedAnalyzingCompiler.scala:188)
	at sbt.compiler.MixedAnalyzingCompiler$.searchClasspathAndLookup(MixedAnalyzingCompiler.scala:166)
	at sbt.compiler.MixedAnalyzingCompiler$.apply(MixedAnalyzingCompiler.scala:176)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:155)
	at sbt.Compiler$.compile(Compiler.scala:141)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:879)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:870)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:868)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (compile:compileIncremental) java.lang.NullPointerException
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? r
```

I'm using sbt 1.3.8, but the same error occurs if I do
```sh
sbt --sbt-version 0.13.13 compile
```

**Comment by nightscape** [comment]
Hmm, interesting...
The build definition is rather straightforward and doesn't do any path magic.
The problem seems to happen in the `project` sub-folder. Did you run SBT in that folder, or is that just SBT itself reading the meta-build?

**Comment by jamesmcnamara** [comment]
Ahh running it in the scalagen directory did get further, thank you!

However now it runs into a new error:
```
[info] Loading project definition from /home/james/projects/scalagen/scalagen/project
[info] Loading settings for project scalagen from build.sbt ...
[info] Set current project to scalagen (in build file:/home/james/projects/scalagen/scalagen/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.jsuereth:scala-arm_2.12:1.4
[error]   Not found
[error]   Not found
[error]   not found: /home/james/.ivy2/local/com.jsuereth/scala-arm_2.12/1.4/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/jsuereth/scala-arm_2.12/1.4/scala-arm_2.12-1.4.pom
[error] Error downloading com.geirsson:scalafmt_2.12:0.5.1
[error]   Not found
[error]   Not found
[error]   not found: /home/james/.ivy2/local/com.geirsson/scalafmt_2.12/0.5.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/geirsson/scalafmt_2.12/0.5.1/scalafmt_2.12-0.5.1.pom
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:246)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:215)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:215)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2947)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.jsuereth:scala-arm_2.12:1.4
[error]   Not found
[error]   Not found
[error]   not found: /home/james/.ivy2/local/com.jsuereth/scala-arm_2.12/1.4/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/jsuereth/scala-arm_2.12/1.4/scala-arm_2.12-1.4.pom
[error] Error downloading com.geirsson:scalafmt_2.12:0.5.1
[error]   Not found
[error]   Not found
[error]   not found: /home/james/.ivy2/local/com.geirsson/scalafmt_2.12/0.5.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/geirsson/scalafmt_2.12/0.5.1/scalafmt_2.12-0.5.1.pom
[error] Total time: 2 s, completed Feb 9, 2020, 3:10:37 PM
```

If I update scala-arm to 2.0, it still complains about the scala fmt dependency, and when I check out [this repo](https://github.com/scalameta/scalafmt) It seems like it might now support sbt 0.13.x anymore? But still doesn't explain where the old binary went.

**Comment by er1c** [comment]
@jamesmcnamara I think this is resolved, or I am able to run everything (make sure you use jdk8), is this safe to close?
